name: check_scripts

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install system packets
      run: |
        sudo apt update
        sudo apt install --yes flake8 mypy pylint3 shellcheck libpython3.7-dev python3-numpy
    - name: install pip packets
      run: pip install onnx==1.7.0 fpbinary==1.5.2
    - name: run_checks
      run: |
        SITE_PKG_PATH=$(python3 -c "import os; import onnx; print(os.path.join(os.sep, *onnx.__file__.split('/')[:-2]))")
        export PYTHONPATH="$SITE_PKG_PATH:$(pwd)/code/python_tools"
        code/snippets/check_scripts.sh .
