name: check_scripts

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install system packets
      run: |
        sudo apt update
        sudo apt install --yes flake8 mypy shellcheck libpython3.7-dev python3-dev python3-numpy
    - name: install pip packets
      run: pip install onnx==1.7.0 fpbinary==1.5.2 pylint==2.4.4
    - name: run_checks
      run: |
        export PYTHONPATH="$(pwd)/code/python_tools"
        code/snippets/check_scripts.sh .
