name: synthesis

on: [push, pull_request]

jobs:
  synthesis:
    runs-on: ubuntu-latest
    container: ghdl/synth:beta
    steps:
      - uses: actions/checkout@v2
      - name: install system packets (for fpbinary)
        run: |
          apt update
          apt install --yes python3-dev
      - name: install onnx
        run: |
          apt update
          apt install --yes python3-pip
          pip3 install onnx==1.7.0 fpbinary==1.5.2
      - name: Run synthesis
        run: |
          export PYTHONPATH="$(pwd)/code/python_tools"
          code/vhdl/syn/synthesize.sh .
