name: testsuite

on: [push, pull_request]

jobs:
  container:
    runs-on: ubuntu-latest
    container: ghdl/vunit:gcc-master
    steps:
      - uses: actions/checkout@v2
      - name: install pip packets
        run: pip install onnx==1.7.0 fpbinary==1.5.2
      - name: Run tests
        run: |
          export PYTHONPATH="$(pwd)/code/python_tools"
          cd code/vhdl/sim/vunit
          python3 run_all.py -p4
      - uses: codecov/codecov-action@v1
        with:
          file: code/vhdl/sim/vunit/coverage.info
